[package]
name = "fkesh"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.31"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tempfile = "3.3"

log = "0.4"

[dev-dependencies]
env_logger = "0.8"